### ISSUE TITLE
Failed login with [*] getCookie: failed

### ISSUE THREAD

**Issue by seokbeomKim** [carpedm20/ndrive#2]
Hi, I've interested in your project and I want to test the program firstly but it failed to login with following messages:

Id: sbk866
Password: 
[*] Error getCookie: failed
Failed lgoin: wrong Id or Password
(Cmd) 

Would you describe about the error message?

**Comment by seokbeomKim** [comment]
It seems like the code has a problem with regexp in 'auth.py' file. I found that the 'host' value is always set to 'https'.
I'm curious about what expected values of 'host' and 'url' are.. can you tell me about "expected values'?

**Comment by carpedm20** [comment]
I found that this library does not work right now. The reason can be various but I think there might be some change in encrypting password of users (maybe related to [login.long.js](https://github.com/carpedm20/ndrive/blob/master/ndrive/login.long.js))

In case of auth.py, I didn't implement the core algorithm as I described in https://github.com/carpedm20/ndrive/blob/master/ndrive/auth.py#L2. You might be find some useful information from http://acuros.tistory.com/?p=198.

Even though NAVER didn't share any information about Ndrive API, we can see the HTTP requests when we use Ndrive on browsers. I use [mitmproxy](https://mitmproxy.org/) to see Ndrive protocol and implement this library.

**Comment by seokbeomKim** [comment]
Thank you for quick reply and useful information.
Received data(url) redirects to page named 'cookienotallowed.nhn(..blabla)'. I should spend more time to find out solution for this issue.
